### ISSUE TITLE
分析镜像profile时出错

### ISSUE THREAD

**Issue by Nixiabing** [Randark-JMT/memory-image-auto-analyzer#1]
![image](https://github.com/Randark-JMT/memory-image-auto-analyzer/assets/20591728/3fea9898-489f-40b2-8f87-c2109557c8a1)

正常情况下：
![image](https://github.com/Randark-JMT/memory-image-auto-analyzer/assets/20591728/7adc1848-460b-4147-ad38-3a871b174b02)

**Comment by Randark-JMT** [comment]
除了日志输出，命令行内有报错信息吗

**Comment by Nixiabing** [comment]
![image](https://github.com/Randark-JMT/memory-image-auto-analyzer/assets/20591728/e520526c-a0ef-454f-9400-f760e80c9a99)

一直就是这么个状态

**Comment by Randark-JMT** [comment]
我可能知道哪里出了问题了，问题可能与WIndows下的路径分隔符与中文有关，由于我之前是在Linux环境下进行开发的，所以还没有遇到过这个问题

我将在下一个提交中解决这个问题

**Comment by Nixiabing** [comment]
我换了下英文路径好像也还是不行。。
还是谢谢了
